server:
  servlet:
    context-path: /v1/api
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:src/main/resources/db/migration
    repeatable-sql-migration-prefix:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/warehouse"
    username: steve
    password: steve

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger
auth:
  whitelist:
    - /auth/**
    - /docs/**
  jwt:
    prefix: Bearer
    key: f85K#VzHazQFby$cal1b%gXAxnZ@JqV^JHiUPPg!lev8IyGeWzNBs8*rCNJ$MTuela0f9&8lOJNy*Y#G9o$&cl#WWA4l8d4zdwU
    expiration: 10

logging:
  level:
#    root: debug
    org.springframework.security: info

hibernate:
  enable_lazy_load
