server:
  servlet:
    context-path: /v1/api
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:src/main/resources/db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/inventory"
    username: test
    password: test

auth:
  whitelist:
    - /auth/**
  jwt:
    prefix: Bearer
    key: f85K#VzHazQFby$cal1b%gXAxnZ@JqV^JHiUPPg!lev8IyGeWzNBs8*rCNJ$MTuela0f9&8lOJNy*Y#G9o$&cl#WWA4l8d4zdwU
    expiration: 10

logging:
  level:
#    root: debug
    org.springframework.security: DEBUG
